// <auto-generated />
namespace E_CommercePlatform.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Refactor_BaseEntity_CategoryEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Refactor_BaseEntity_CategoryEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202505151217083_Refactor_BaseEntity_CategoryEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
